#!/bin/bash

# compile the java files
javac -d . Tools/Formatter.java
javac -d . Tools/Reader.java
javac -d . Tools/Variable.java
javac -d . Tools/PropositionalLogic.java
javac Wrapper.java

echo Enter a swc file:

read fileName

echo Enter the number of solutions you want:

read k_val

# make sure there is no UCS-input, or output file
rm UCS-input.txt
rm wcsp-output.txt

# store the location of WCSPLift 
wcsp_location=../../401/wcsp-solver/bin

# call the actual wrapper class with the correct filename
java Wrapper $fileName

	# by this point, the Wrapper should have created a UCS-input.txt
	
python3 top_k/main.py -p $wcsp_location/wcsp -L -f ./UCS-input.txt -K $k_val >> wcsp-output.txt 

# run python read_results script
python Tools/read_results.py $fileName
